apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ansible-cicd-ingress
  namespace: staging
  labels:
    app: ansible-cicd
    environment: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: ansible-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ansible-cicd-service
                port:
                  number: 80
